In [2]:
import numpy as np
import tensorflow as tf 

In [3]:
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
# 创建int32类型的0维张量，即标量
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
# 创建float32类型的1维张量
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)
# 创建float16类型的⼆维张量
rank_2_tensor = tf.constant([[1, 2],
 [3, 4],
 [5, 6]], dtype=tf.float16)
print(rank_2_tensor)
# 创建float32类型的张量
rank_3_tensor = tf.constant([
 [[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9]],
 [[10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19]],
 [[20, 21, 22, 23, 24],
 [25, 26, 27, 28, 29]],], dtype=tf.float32)
print(rank_3_tensor)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)
tf.Tensor(
[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]]

 [[10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]]], shape=(3, 2, 5), dtype=float32)


#转换成numpy

In [5]:
tensor1=tf.constant([1,23,48,5649])

In [6]:
tensor1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([   1,   23,   48, 5649])>

In [7]:
tensor1.numpy()

array([   1,   23,   48, 5649])

#常用函数

In [8]:
# 定义张量a和b
a = tf.constant([[1, 2],
 [3, 4]])
b = tf.constant([[1, 1],
 [1, 1]]) 
print(tf.add(a, b), "\n") # 计算张量的和
print(tf.multiply(a, b), "\n") # 计算张量的元素乘法
print(tf.matmul(a, b), "\n") # 计算乘法


tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [9]:
c=tf.constant([[1,2,3],
               [4,5,6],
               [7,8,9]])
c

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [10]:
#最大值
tf.reduce_max(c)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [12]:
#变量
var=tf.Variable([[1,2,3],[4,5,6]])

In [13]:
var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [14]:
var.shape

TensorShape([2, 3])

In [15]:
var.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
var.assign([[4,5,6],[7,8,9]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9]])>